spring:
  application:
    name: enotes-api-service
  profiles:
    active: test

file:
  upload:
    path: notes/

# ---------------- DEV ----------------
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: mukeshlabana844@gmail.com
    password: wfho kisl ezam ltol
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/

# ---------------- PROD ----------------
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: mukeshlabana844@gmail.com
    password: wfho kisl ezam ltol
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/

# ---------------- UAT ----------------
---
spring:
  config:
    activate:
      on-profile: uat

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: mukeshlabana844@gmail.com
    password: wfho kisl ezam ltol
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/

# ---------------- TEST ----------------
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: mukeshlabana844@gmail.com
    password: wfho kisl ezam ltol
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/