spring.application.name=Enotes_Api_Service

spring.datasource.url=jdbc:mysql://localhost:3306/enotes
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
file.upload.path=notes/

#Email send config
spring.mail.host=smtp.gmail.com
spring.mail.username=mukeshlabana844@gmail.com
spring.mail.password=wfho kisl ezam ltol
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true